### ISSUE TITLE
Exporting entire sequences of combined characters

### ISSUE THREAD

**Issue by maelgr** [DatabaseGroup/DeSignate#1]
Hi,
It would be great if, as well as giving us the position and state of the first and last character of a combined character, the software could output the whole sequence. It would be very useful when using long k-windows for many species and when there are many combined characters.
Cheers!

**Comment by thuetter** [comment]
Hi, 
thank you for posting your question.
I am not sure whether I understood your question correctly. Combined characters are currently only supported for pairs of character states due to the comutational complexity. Hence, combined mocular characters consist of two character states and are independent of the character states between them.
Are there any particular use cases that we are not aware of? 
I am looking forward hearing from you. Cheers!

**Comment by maelgr** [comment]
Hi,
Sorry, then I guessed it's me who misunderstood this part of the software. I thought it was able to look for longer strings. A bit like designing a species specific primer, but making sure to exclude all other species. It's much clearer now, thanks! 
Although, it may be possible to get a short diagnostic sequence if the region between two combined characters is conserved in the query group?
We have been thinking a lot with my colleagues about how to integrate these combined characters in formal diagnosis, because with long k-windows there can be many....
Thanks again!

**Comment by thuetter** [comment]
Hi, 
No worries. The concept of combining multiple character states, however, is extensible to multiple positions. In terms of complexity, the runtime is increasing exponentially, e.g., looking up combinations of three character states takes cubic runtime. That is the reason why we only included the combination of two character states for now.
Yes, that's a good point. Right now, our tool does not specifically highlight longer sequences; each character state is highlighted individually. If looking for long sequences is of special interest, we can consider it a feature request for a future version.

**Comment by thuetter** [comment]
May I consider this issue as closed?

**Comment by maelgr** [comment]
yes, thank you for your help.
