### ISSUE TITLE
Tree won't load in DeSignate

### ISSUE THREAD

**Issue by maxganser** [DatabaseGroup/DeSignate#2]
Currently, there is a little bug causing DeSignate to not load the tree (Group selection tree window is blank) if there is an empty line in the treefile:
![image](https://user-images.githubusercontent.com/78967298/107779236-5cadd800-6d45-11eb-9874-bac471b31e25.png)

Solution: 
Just remove the empty line with a text editor (e.g., Notepad++).

**Comment by thuetter** [comment]
Thanks for the comment. We fixed this bug in the current version.
Can you confirm? Then we will close this issue.

**Comment by maxganser** [comment]
Confirmed. Thanks!
